# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2459011a8cd8a36a00ac244078fd5f421ad28ccf4f3123cc4a5e1da87641b5606689d695a1ff6cce849f9b29fdc030db3b90941d1542d493913ea0c8ced0b78d

test:
  secret_key_base: 35d01ec5e8e3fd7fa792e4a560ad55c45ef8c40a08b6ed98cc42c276c63a05d30ec990213e43cc6e11a681a14c1afaddec1f4c039903190b3152f477b995ed66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
